## TOML Uranio
db = "mongo"
token_expire_seconds = 604800 # 1 week
auth_cookie_expire_seconds = 604800 # 1 week
encryption_rounds = 12
max_password_length = 58
storage = 'aws'
connect_on_init = false
prefix_api = '/uranio/api'
prefix_log = '/logs'
lambda = 'netlify'
[default_atoms]
	superuser = true
	group = true
	user = false
	media = false
	request = true
	error = true
[service]
	platform = 'express'
	protocol = 'http'
	domain = 'localhost'
	port = 7772
	url = 'http://localhost:7772/uranio/api'
[dev.service]
	protocol = 'http'
	domain = 'localhost'
	port = 7772
	url = 'http://localhost:7772/uranio/api'
[log]
	debug_info = true
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[dev.log]
	debug_info = false
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[client.log]
	debug_info = false
	color = true
	time_format = "HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
[client.dev.log]
	debug_info = false
	color = true
	time_format = "yyyy-mm-dd'T'HH:MM:ss:l"
	max_str_length = 174
	prefix = ''
	prefix_type = false
